default: &default
  adapter: sqlite3
  encoding: utf8
  pool: 5

development:
  <<: *default
  database: db/animals_development.sqlite3

production:
  <<: *default
  database: db/animals_production.sqlite3

test:
  <<: *default
  database: db/animals_test.sqlite3